### ISSUE TITLE
Integrate with astropy and aplpy

### ISSUE THREAD

**Issue by rpmunoz** [gbrunner/Map-of-the-Sky#1]
# Great work. I've been processing large astronomical images during the last years and have found that astropy+aplpy can be used for creating great color images of diffuse and low surface brightness objects in the sky. Take a look to https://github.com/rpmunoz/Astronomy/tree/master/RGB%20images and http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:1510.02475

I will fork you repository and will try to integrate astropy+aplpy+arcpy. What do you think?

**Comment by gbrunner** [comment]
@jwasilgeo Let's add a basemap switcher to toggle between these 3 maps 
- http://tiles.arcgis.com/tiles/g2TonOxuRkIqSOFx/arcgis/rest/services/Galactic_Plane_Faint/MapServer
- http://tiles.arcgis.com/tiles/g2TonOxuRkIqSOFx/arcgis/rest/services/Galactic_Plane/MapServer
- http://tiles.arcgis.com/tiles/g2TonOxuRkIqSOFx/arcgis/rest/services/Galactic_Plane_Bright/MapServer

**Comment by gbrunner** [comment]
@jwasilgeo Can we put a black background over the globe, kind of like Heather Smith has in her star chart?
- http://www.arcgis.com/home/webmap/viewer.html?webmap=7e8032ace3f94a4aac161522bee7996d

**Comment by gbrunner** [comment]
@jwasilgeo can we put Heather Smith's entire star chart on the globe?
- http://www.arcgis.com/home/webmap/viewer.html?webmap=7e8032ace3f94a4aac161522bee7996d

**Comment by gbrunner** [comment]
@jwasilgeo I will publish a feature service of stars\bright objects. After that, let's overlay them on the map of the sky.
