### ISSUE TITLE
Add Basemap Switcher

### ISSUE THREAD

**Issue by gbrunner** [gbrunner/Map-of-the-Sky#3]
@jwasilgeo Let's add a basemap switcher to toggle between these 3 maps

- http://tiles.arcgis.com/tiles/g2TonOxuRkIqSOFx/arcgis/rest/services/Galactic_Plane_Faint/MapServer
- http://tiles.arcgis.com/tiles/g2TonOxuRkIqSOFx/arcgis/rest/services/Galactic_Plane/MapServer
- http://tiles.arcgis.com/tiles/g2TonOxuRkIqSOFx/arcgis/rest/services/Galactic_Plane_Bright/MapServer

**Comment by jwasilgeo** [comment]
@ycabon your custom `BlackLayer` continues to serve us well in this app!  I found this workaround, however, for keeping it in place on the Map when switching basemaps with the BasemapGallery widget. Just in case you're curious; no requests at the moment.  😄 

https://github.com/gbrunner/Map-of-the-Sky/blob/1fe3e26d02e25bb031615d42f9a12d4fd0fa52fd/docs/script.js#L113-L118
